[2023-09-14 12:36:34,092][ignite.engine.engine.Engine][INFO] - Engine run starting with max_epochs=1.
[2023-09-14 12:36:34,391][ignite.engine.engine.Engine][ERROR] - Current run is terminating due to exception: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/seppanen/miniconda3/envs/bts/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/seppanen/miniconda3/envs/bts/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/seppanen/miniconda3/envs/bts/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/seppanen/mbts/datasets/kitti_360/kitti_360_dataset.py", line 799, in __getitem__
    bev = [self.load_bev_segmentations(sequence, img_ids[0])]
  File "/home/seppanen/mbts/datasets/kitti_360/kitti_360_dataset.py", line 693, in load_bev_segmentations
    cat_out, iscrowd_out, ids_out, sem_out = self._prepare_inputs(self, msk=bev, cat=bev_cat, iscrowd=bev_iscrowd, front=False)
  File "/home/seppanen/mbts/datasets/kitti_360/kitti_360_dataset.py", line 520, in _prepare_inputs
    msk_i = msk_i.squeeze(0)
ValueError: cannot select an axis to squeeze out which has size not equal to one

[2023-09-14 12:36:34,392][ignite.engine.engine.Engine][ERROR] - Engine run is terminating due to exception: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/seppanen/miniconda3/envs/bts/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/seppanen/miniconda3/envs/bts/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/seppanen/miniconda3/envs/bts/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/seppanen/mbts/datasets/kitti_360/kitti_360_dataset.py", line 799, in __getitem__
    bev = [self.load_bev_segmentations(sequence, img_ids[0])]
  File "/home/seppanen/mbts/datasets/kitti_360/kitti_360_dataset.py", line 693, in load_bev_segmentations
    cat_out, iscrowd_out, ids_out, sem_out = self._prepare_inputs(self, msk=bev, cat=bev_cat, iscrowd=bev_iscrowd, front=False)
  File "/home/seppanen/mbts/datasets/kitti_360/kitti_360_dataset.py", line 520, in _prepare_inputs
    msk_i = msk_i.squeeze(0)
ValueError: cannot select an axis to squeeze out which has size not equal to one

