[2023-09-20 16:50:34,487][ignite.engine.engine.Engine][INFO] - Engine run starting with max_epochs=1.
[2023-09-20 16:50:34,799][ignite.engine.engine.Engine][ERROR] - Current run is terminating due to exception: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/seppanen/miniconda3/envs/bts/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/seppanen/miniconda3/envs/bts/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/seppanen/miniconda3/envs/bts/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/seppanen/mbts/datasets/kitti_360/kitti_360_dataset.py", line 779, in __getitem__
    vox_seg = [self.load_vox_segmentations(sequence, img_ids[0])]
  File "/home/seppanen/mbts/datasets/kitti_360/kitti_360_dataset.py", line 669, in load_vox_segmentations
    voxel = self.lut[voxel]
IndexError: arrays used as indices must be of integer (or boolean) type

[2023-09-20 16:50:34,800][ignite.engine.engine.Engine][ERROR] - Engine run is terminating due to exception: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/seppanen/miniconda3/envs/bts/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/seppanen/miniconda3/envs/bts/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/seppanen/miniconda3/envs/bts/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/seppanen/mbts/datasets/kitti_360/kitti_360_dataset.py", line 779, in __getitem__
    vox_seg = [self.load_vox_segmentations(sequence, img_ids[0])]
  File "/home/seppanen/mbts/datasets/kitti_360/kitti_360_dataset.py", line 669, in load_vox_segmentations
    voxel = self.lut[voxel]
IndexError: arrays used as indices must be of integer (or boolean) type

