[2023-08-22 10:46:27,360][ignite.engine.engine.Engine][INFO] - Engine run starting with max_epochs=1.
[2023-08-22 10:46:29,769][ignite.engine.engine.Engine][ERROR] - Current run is terminating due to exception: cusolver error: CUSOLVER_STATUS_INTERNAL_ERROR, when calling `cusolverDnCreate(handle)`
[2023-08-22 10:46:29,827][ignite.engine.engine.Engine][ERROR] - Engine run is terminating due to exception: cusolver error: CUSOLVER_STATUS_INTERNAL_ERROR, when calling `cusolverDnCreate(handle)`
